name: PDF generation

on:
  push:
    branches: [main]

jobs:
  make-pdf:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        pcb_layers: ['F.Cu', 'F.Silkscreen', 'B.Cu', 'B.Silkscreen']
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.3'

      - name: Install kicad with kikit
        run: |
          sudo apt update
          sudo add-apt-repository --yes ppa:kicad/kicad-7.0-releases
          sudo apt update
          sudo apt install --install-recommends kicad
          sudo apt install
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install kikit

      - name: Getting the empty respository
        uses: actions/checkout@v3
        with:
          ref: 'pdfs'
          path: './pdfs'

      - name: Clean pdfs/ directory
        run: |
          rm -rf pdfs/*

      - name: Making schematics
        run: |
          mkdir -p pdfs/schematics/
          kicad-cli sch export pdf RPiHat/RPiHatHVLVPower/RPiHatHVLVPower.kicad_sch --output ./pdfs/schematics/RPiHatHVLVPower.pdf
          kicad-cli sch export pdf RPiHat/RPiHatSensor/RPiHatSensor.kicad_sch       --output ./pdfs/schematics/RPiHatSensor.pdf
          kicad-cli sch export pdf LEDPulser/LEDPulser.kicad_sch                    --output ./pdfs/schematics/LEDPulser.pdf

      - name: Making single PCBs
        run: |
          mkdir -p pdfs/PCBsingle/
          kicad-cli pcb export pdf LEDPulser/LEDPulser.kicad_pcb                    --layers=${{matrix.pcb_layers}} --output ./pdfs/PCBsingle/LEDPulser.${{matrix.pcb_layer}}.pdf
          kicad-cli pcb export pdf RPiHat/RPiHatSensor/RPiHatSensor.kicad_pcb       --layers=${{matrix.pcb_layers}} --output ./pdfs/PCBsingle/RPiHatSensor.${{matrix.pcb_layer}}.pdf
          kicad-cli pcb export pdf RPiHat/RPiHatHVLVPower/RPiHatHVLVPower.kicad_pcb --layers=${{matrix.pcb_layers}} --output ./pdfs/PCBsingle/RPiHatHVLVPower.${{matrix.pcb_layer}}.pdf

      - name: Making panel PCBs
        run: |
          mkdir -p pdfs/PCBPanels/
          cd Panel/
          bash ./kikit_script.py
          cd ../
          kicad-cli pcb export pdf Panel/panel_LEDPulser.kicad_pcb --layers=${{matrix.pcb_layers}} --output ./pdfs/PCBPanels/LEDPulser.${{matrix.pcb_layer}}.pdf
          kicad-cli pcb export pdf Panel/panel_Sensor.kicad_pcb    --layers=${{matrix.pcb_layers}} --output ./pdfs/PCBPanels/RPiHatSensor.${{matrix.pcb_layer}}.pdf
          kicad-cli pcb export pdf panel_HVLVPower.kicad_pcb       --layers=${{matrix.pcb_layers}} --output ./pdfs/PCBPanels/RPiHatHVLVPower.${{matrix.pcb_layer}}.pdf

      - name: Pushing to public PDF pages
        run: |
          git add --all
          git commit -m "Updated from Github actions"
          git push origin pdfs
