name: PDF generation

on:
  push:
    branches: [main]

jobs:
  make-pdf:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        pcb_layers: ['F.Cu', 'F.Silkscreen', 'B.Cu', 'B.Silkscreen']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.3"
      - name: Install kicad with kikit
        run: |
          sudo apt update
          sudo add-apt-repository --yes ppa:kicad/kicad-7.0-releases
          sudo apt update
          sudo apt install --install-recommends kicad
          sudo apt install
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install kikit
      - name: Making schematics
        run: |
          mkdir -p prints/schematics/
          kicad-cli sch export pdf RPiHat/RPiHatHVLVPower/RPiHatHVLVPower.kicad_sch --output ./prints/schematics/RPiHatHVLVPower.pdf
          kicad-cli sch export pdf RPiHat/RPiHatSensor/RPiHatSensor.kicad_sch       --output ./prints/schematics/RPiHatSensor.pdf
          kicad-cli sch export pdf LEDPulser/LEDPulser.kicad_sch                    --output ./prints/schematics/LEDPulser.pdf
      - name: Making single PCBs
        run: |
          mkdir -p prints/PCBsingle/
          kicad-cli pcb export pdf LEDPulser/LEDPulser.kicad_pcb                    --layers=${{matrix.pcb_layer}} --output ./prints/PCBsingle/LEDPulser.${{matrix.pcb_layer}}.pdf
          kicad-cli pcb export pdf RPiHat/RPiHatSensor/RPiHatSensor.kicad_pcb       --layers=${{matrix.pcb_layer}} --output ./prints/PCBsingle/RPiHatSensor.${{matrix.pcb_layer}}.pdf
          kicad-cli pcb export pdf RPiHat/RPiHatHVLVPower/RPiHatHVLVPower.kicad_pcb --layers=${{matrix.pcb_layer}} --output ./prints/PCBsingle/RPiHatHVLVPower.${{matrix.pcb_layer}}.pdf
      - name: Making panel PCBs
        run: |
          mkdir -p prints/PCBPanels/
          cd Panel/
          bash ./kicad/kikit_script.py
          cd ../
          kicad-cli pcb export pdf Panel/panel_LEDPulser.kicad_pcb --layers=${{matrix.pcb_layer}} --output ./prints/PCBPanels/LEDPulser.${{matrix.pcb_layer}}.pdf
          kicad-cli pcb export pdf Panel/panel_Sensor.kicad_pcb    --layers=${{matrix.pcb_layer}} --output ./prints/PCBPanels/RPiHatSensor.${{matrix.pcb_layer}}.pdf
          kicad-cli pcb export pdf panel_HVLVPower.kicad_pcb       --layers=${{matrix.pcb_layer}} --output ./prints/PCBPanels/RPiHatHVLVPower.${{matrix.pcb_layer}}.pdf
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./prints
